name: Build and deploy

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm ğŸ“¥
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js ğŸ“¥
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies ğŸ“¥
        run: pnpm install

      - name: Build plugins ğŸ› ï¸
        run: |
          mkdir -p .dist
          pnpm run build
          for plugin in plugins/*
          do
            if [ -d "$plugin/dist" ]; then
              cp -r "$plugin/dist" ".dist/$(basename $plugin)"
            else
              echo "Directory $plugin/dist does not exist skipping..."
            fi
          done

      - name: Copy themes folder ğŸ“
        run: |
          cp -r themes .dist/themes

      - name: Upload artifact ğŸ“¡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    if: github.ref == 'refs/heads/master'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages ğŸš€
        id: deployment
        uses: actions/deploy-pages@v4
